### PR TITLE
Expenses fix plus more

### PR DESCRIPTION
**Pull request by mistergone**
This PR **fixes the expenses calculations** so you should see green functional tests across the board. It also moves the `nationalData` retrieval to an AJAX call for the API endpoint.
## Removals
- `get-school-values.js` was removed, since all of its functions have been moved to other files
## Changes
- The expenses section is now properly updated by the code.
- Values for monthly expenses from BLS are rounded after being divided
- `nationalData` is now retrieved from our API endpoint via AJAX and compiled in the school model (and copied to the financial model, as well)
- Fix for percentage values of default rate
## Testing
- Pull it down, do the `loaddata` dance, and `gulp`, then check out the functional and unit tests!
- Oh, you can also go in there and play around with the expenses section, if you're into that.
## Review
- @marteki @niqjohnson @higs4281 
## Screenshots

screen shot 2016-02-25 at 12 01 23 pm
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [ ] Visually tested in supported browsers and devices 
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
## Animated GIF

**All functional tests passing is like...**

it-crowd-dance

### CODE REVIEW

**Comment by higs4281** [comment]
:+1:  graphs and values showing up for me.  npm tests green. one functional test fails for me, on the scorecard link. 
Wish I were a browser so I would be told repeatedly to sleep.

**Comment by marteki** [comment]
anchorman-yes-jumping

harry-potter

gif-dancing-celebrate-celebration-dance-ecstatic-happy-happy-dance-joy-success-woo-hoo-gif

In other words, :+1:
I got zero functional test failures. :tada:

**Comment by niqjohnson** [comment]
:+1: 

All tests passing for me, too!

A few to-dos for later (I can open issues on these if that's helpful):
- The "Student loans" line item in the expenses worksheet shows "$0". That's not supposed to work as part of this PR, right?
- I get two lint errors in get-api-values, but they don't seem to be breaking anything

**Comment by mistergone** [comment]
@niqjohnson - I didn't address student loans, no. And I don't know how I missed the linter errors, but I'll fix them before my next PR.

**Mergin' this!**

**Pull request merged**
