### PR TITLE
Large-screen forms styles

### PR DESCRIPTION
**Pull request by niqjohnson**
Add large-screen styles for step 1 and the offer and expenses forms
## Additions
- Step 1 and forms LESS for screens wider than `@bp-sm-min` (600px)
## Changes
- HTML changes to accommodate the large-screen design
## Testing
- To test, pull in the `forms-large` branch and run `gulp`. Fire up the app in standalone or UnityBox as normal. The page will be at `/paying-for-college2/demo`.
- I've tested this in IE8/Win7, IE9/Win7, IE11/Win7, Firefox/Win7, Chrome/Mac, Safari/Mac, Mobile Safari/iPhone6, and everything seems to be looking good
## Review
- @ascott1
- @mistergone 
- @marteki 
### Step 1

| 600px and under | 601px and above |
| --- | --- |
| step-1-small | step-1-large |
### Monthly expenses

| 600px and under | 601px and above |
| --- | --- |
| expenses-small | expenses-large |
## Todos
- Make "big picture" summary boxes sticky on large screens
## Checklist
- [X] Changes are limited to a single goal (no scope creep)
- [X] Code can be automatically merged (no conflicts)
- [X] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [X] Passes all existing automated tests
- [X] Placeholder code is flagged
- [X] Visually tested in supported browsers and devices

### CODE REVIEW

**Comment by ascott1** [comment]
:heart_eyes: :+1:

**Comment by Chaeny** [comment]
It looks soooo purrrrty!  I'm happy with how you have laid out all the key fields and kept the total visually close to the "edit" fields without cluttering the space.

**Comment by higs4281** [comment]
:+1:

**Comment by marteki** [comment]
Working as expected on standalone Mac Chrome, Unitybox Mac Chrome, and Android 6.0 Chrome beta.

:+1: :+1:, way up.

**Comment by niqjohnson** [comment]
## Changes
- Added IDs to summary fields to make functional tests work

## Review
- @ascott1, @mistergone, @marteki: Mind reviewing again to make sure everything looks good and all tests are passing?

**Comment by marteki** [comment]
Page looks good, tests all passed. I put a minor comment for the test conf file (which I'm sure is actually my bad). Even if that doesn't get fixed in this PR, :+1: from me.

**Comment by niqjohnson** [comment]
EOF newline added to `conf.js`

**Comment by ascott1** [comment]
Fresh :+1: from me

**Pull request merged**
