### PR TITLE
Make the content even more dynamic

### PR DESCRIPTION
**Pull request by marteki**
Makes it so that values in the textual page content are dynamic for many things, and removes several items from loans that aren't going to be included in the tool.
## Additions
- Pulls the school and program data from the Django-delivered on-page JS into the main model.
- Include completion rate as something separate from graduation rate
## Removals
- Content about national debt average
- UI for loan grace and deferment periods, as well as functional tests
- Content about BLS expenses being "for a single person"
- Content in step 3 tied to header "If you want to make a change"
## Changes
- As wisely pointed out by @mistergone, checks for window.\* property existence before trying to check the values of attributes on said properties
- Pull the following items from data instead of being hard-coded:
  - federal loan rates
  - total median debt at school
  - job placement rate
  - default rate
  - median salary for program or school
  - BLS monthly expenses
- Change the following wording depending on data:
  - program length in words ("two" instead of 2)
  - "National" vs. "[specific region] regional" displayed for BLS expenses
## Testing
- To test: pull in the `dynamic-content` branch. Run `npm install` (to pull in the newly added number-to-words package), then run `gulp`. Fire up the app in standalone or UnityBox as normal.
- Six Part 2 tests are still failing, because the total monthly estimated values are not being updated. :cry:  You should see something similar to:

> 48 specs, 6 failures
> Finished in 77.683 seconds
## Review
- @mistergone @niqjohnson @higs4281 and @kurzn 
## Todos
- Remove paragraphs or sentences based on no data being passed (completion rate, job placement rate, etc.)
- Show or hide paragraphs based on offer calculations
- Pull in default private loan rate of 7.9% (in model, but not being transferred to inputs properly) and default private loan fee of 4.9% (not in model)
## Checklist
- [x] CHANGELOG has been updated
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [ ] Passes all existing automated tests
- [x] New functions include new tests
- [x] Placeholder code is flagged

### CODE REVIEW

**Comment by marteki** [comment]
UI reviewed by @kurzn and @caheberer. After the removal of one no-longer-dynamic header and paragraph in Step 3, they say the content updates look as they were expecting. :smile:

**Comment by mistergone** [comment]
:+1:

**Comment by marteki** [comment]
Pushed some improvements suggested by @mistergone, that helps make the code more robust for the eventual non-settlement student path. :grin:

**Comment by mistergone** [comment]
Fix for the merge conflict is in my repo, on the `dynamic-content` branch:
https://github.com/mistergone/college-costs/tree/dynamic-content

**Comment by mistergone** [comment]
I am hereby commandeering this Pull Request. Sorry, @marteki, but I figure pushing my own code up here is fairly benign. :smile:

**Comment by niqjohnson** [comment]
:+1:

**Comment by mistergone** [comment]
Merging!

**Pull request merged**
