### PR TITLE
Update all content throughout the tool, refactor the expenses section, and split apart private loans from tuition payment plans

### PR DESCRIPTION
**Pull request by marteki**
**Warning:** this is the opposite of a compact PR. Many things are included here.

I'm pushing this work out before it's finalized and perfect so @mistergone has it for _his_ work.
## Additions
- Separate out private loans and tuition payment plans in the HTML/CSS
## Removals
- JS functions for combining family contributions with Parent PLUS loans
## Changes
- Reorder and fix styles in the budget worksheet
- Show and hide content or offer sections depending on the program values and passed URL values
- Update Step 3 illustration for "think about working while you study"
- Update functional browser tests
## Testing

Pull down the branch. Spin it up with some of our sample URLs.
- **The JS hookups for the new private loan and tuition payment plan areas have not been created yet.** They will come in a future PR from @mistergone.
- Partially as a result, **functional browser tests will not all pass.** I get roughly 16 tests failing, but that is dependent on how many timeouts the Selenium server hits. The refactor of all the browser tests will have to come up out of the backlog.
- NPM security tests are not passing, due to the need for package updates.
- All content outside the private loans/payment plan areas should match the cleared content given to the team dated July 11.
- All unit tests should pass.
## Review
- @mistergone @higs4281 @amymok 
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [ ] Passes all existing automated tests
- [ ] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by higs4281** [comment]
#### npm tests
- [x] fail with 1 vuln

#### Verifications
- [x] Verification for "This is not my information" works as expected
- [x] Verification for big question works as expected
- [x] attempt to send 2nd Verification fails as expected

#### Links
- [x] "About" link works (although the About page's sidebar is still missing the "resources" sidebar from Step 3)
- [x] The  "job placement rate" link in Step 2 tries to find "#job-placement-rate" on our "About" page, but there is no such ID --> to be implemented

#### Browser experience
- [x] Year fractions appear correctly
- [x] The sticky-sidebar bump is gone in Chrome!
- [x] The print option is so much improved -- did that come in from CF?
- [x] ~~The "tell us how" button doesn't work for me in Chrome, although the feedback url works for me manually~~ button works

#### Data
- [x] url fields map correctly, barring private loans and payment plans

#### Content
- [x] Typo in Step 2: "money to purchase a care" --> car
- [x] Typo in Step 3: "Changing amounts in this tool has no affect on" --> effect
- [x] Typo in Step 3: "They are not sent to your school and have no affect on" --> effect
- [x] Rest of new content looks great!
- [x] Blue suitcase is blue

**Comment by marteki** [comment]
#### Links

> The "job placement rate" link in Step 2 tries to find "#job-placement-rate" on our "About" page, but there is no such ID

Ah, forgot to point that out in my description! Since the "About This Tool" content has been cleared yet, and the relevant section isn't in the currently deployed text, the link isn't going anywhere. Yet.

#### Browser experience

> The "tell us how" button doesn't work for me in Chrome, although the feedback url works for me manually

Odd. 😕  It works for me, and I didn't touch anything having to do with it at all. @amymok or @mistergone can you confirm that this is broken for you?

#### Content

>  Typo in Step 2: "money to purchase a care" --> car
>  Typo in Step 3: "Changing amounts in this tool has no affect on" --> effect
>  Typo in Step 3: "They are not sent to your school and have no affect on" --> effect

Calling @kurzn, particularly around the 'affect' piece. I have a chat discussion documented from March's usability testing saying that those instances of 'affect' are intentional.

**Comment by higs4281** [comment]
> those instances of 'affect' are intentional

if we want to use 'affect' then we should use "does not affect"  
what is the rationale for an intentional mistake?

Also, the July 11 content doc uses the "do/does not affect" form.

**Comment by higs4281** [comment]
@marteki re "tell us how": my bad. I forgot to turn off a blocker in my browser.

**Comment by amymok** [comment]
I worked on matching the content with the final:
- Estimated years to complete your program
  - [x] The paragraph is not exactly the same as the final ☑️  fixed in commit
  - [x] Final content did not include 6 1/2 years, but is currently in the dropdown menu ☑️  fixed in commit
- Cost of Attendance
  - [x] Remove "." at the end of helper verbiage ☑️  fixed in commit
- Military tuition assistance
  - [x] Move "; see how much the GI Bill pays"to GI Bill ☑️  fixed in commit
- GI Bill
  - [x] Remove ", see if you qualify" ☑️  fixed in commit
- Subsidized loans
  - [x] Assuming the interest rate is calculated so it doesn't match final content ☑️  [Marteki: correct assumption, it's passed in the URL]
- Unsubsidized loans
  - [x] Assuming the interest rate is calculated so it doesn't match final content ☑️  [Marteki: correct assumption, it's passed in the URL]
- Grad PLUS loans
  - [x] Assuming the interest rate is calculated so it doesn't match final content ☑️  [Marteki: correct assumption, it's passed in the URL]
- Private Loans
  - [x] Helper verbiages below Interest Rate is not the same as final content ☑️  fixed in commit
- TUITION PAYMENT PLAN FROM YOUR SCHOOL
  - [x] The last paragraph is different from final content: Payments start while you are in school and the loan must be paid back within [xx] months **[Marteki: updated content is found on internal Github issue 107]**
- What does this mean for your future?
  - [x] The paragraph: Some students find themselves.....: use **leave** instead of **finish** ☑️  fixed in commit
  - [x] Verbiage for remaning cost < $0, missing the word **borrowing** **[Marteki: "borrowing" is in the current text of the PR? I'll re-copy and paste it to make sure.]**  ☑️  fixed in commit
  - [x] Under Big Picture - Remaining Cost: missing **to** in front of **pay** ☑️  fixed in commit
- How many students graduate?
  - [x] In the offer I am looking at, the paragraph has something like: "For first-time students enrolled full-time in Information Technology at South University-Tampa, **None** out of **None** graduated."  Do we need to fix and massage what **None** should be? **[Marteki: run migrate and loaddata collegedata, to grab the completers and completion_cohort]**
- Your salary and total student debt
  - [x] The paragraph doesn't match, use **avoid borrowing** instead of **not borrow**, and missing **for school** between **more than** ☑️  fixed in commit
- How much will I pay per month for all of my student loans?
  - [x] First paragraph, the verbiage is different from final ☑️  fixed in commit
  - [x] The paragraph: "Many of these alternative repayment plans are based on income and family size..." doesn't match with final ☑️  fixed in commit
- See how loan length affects your payments
  - [x] missing radio buttons to toggle 10/25 yrs? **[Per the content doc, this should only appear if the total federal loans for the program length is over $30,000. So increase the federal loan borrowing, and the program length, and see if it's still missing?]**
- How will I afford my loan payment?
  - [x] link to job placement rate: there's no #job-placement-rate in "About this tool" ☑️  see [my reply in this thread to Bill](https://github.com/cfpb/college-costs/pull/214#issuecomment-232430287) about this
- Estimated budget after you leave school (adjust as needed)
  - [x] missing **and their family** in the helper paragraph:  ☑️  fixed in commit
- Your estimated debt burden
  - [x] missing radio buttons? 10/25 years? **[Per the content doc, this should only appear if the total federal loans for the program length is over $30,000. So increase the federal loan borrowing, and the program length, and see if it's still missing?]**
- What if I can’t afford my student loan payments?
  - [x] First helper paragraph is different from final ☑️  fixed in commit
- Step 3: Under "Maximize all available grants and scholarships"
  - [x] link should be on "additional scholarships and grants" only (remove "applying for from the link") ☑️  fixed in commit
  - Step 3: Under "Consider a different program with better outcomes."
  - [x] Helper verbiage is different from final ☑️  fixed in commit
- Step 3: Under "Think about working while you study"
  - [x]  The phase **(even if it’s not related to your field of study)**, is no longer separated by ( ), but by commas ☑️  fixed in commit
- Step 3: Under "What you can do"
  - [x] First paragraph is different ☑️  fixed in commit
  - [x] I think you fixed the effect vs affect ☑️  fixed in commit
- Next steps
  - [x] First paragraph: remove **choose to**
  - [x] Under 1., the 1st heading paragraph is different ☑️  fixed in commit
  - [x] Under 1., the 1st non-heading paragraph is also different ☑️  fixed in commit
  - [x] Under 2., the 1st heading paragraph is different ☑️  fixed in commit

**Comment by mistergone** [comment]
I didn't work on checking each piece of content, but the JS changes look good! 👍

**Comment by marteki** [comment]
> Final content did not include 6 1/2 years, but is currently in the dropdown menu

~~Yeah, that was based on a verbal affirmation that I should increase the dropdown to 6 1/2 years (back when we added half years). Easy to change, but I'd want @saintsoup52 or @serenaestrella to confirm to follow the doc rather than their verbal decision.~~

Per Patrick's comment below, made this change.

>  Cost of Attendance
>  Remove "." at the end of helper verbiage

~~I have a period at the end of the helper text in my content doc.~~

screen shot 2016-07-13 at 2 38 41 pm

~~Is it missing in your copy?~~

I had an old copy. Made this change.

**Comment by marteki** [comment]
Alright, a third revision to the content doc came out when I wasn't looking, and just hit my inbox today. Making changes.

**Comment by kurzn** [comment]
@marteki The period is removed after helper text, since it is not a complete sentence. That was a new edit, from when I made the tuition repayment plan edits on Monday. 

The affect/effect should have been fixed a long time ago and are showing up differently in both the version "FINAL" and "FINAL 7.11.16." 

Please use FINAL 7.11.16.

**Comment by saintsoup52** [comment]
I don't have strong feelings about the 6 yrs vs 6 1/2 years... we had 6 years in the content we sent to EDMC so we should probably just use that.

**Comment by marteki** [comment]
Two things of note:

>  The sticky-sidebar bump is gone in Chrome!
>  The print option is so much improved -- did that come in from CF?

I touched neither of these items. I will take the improvements where I can get them, though.

**Comment by marteki** [comment]
@amymok I think I addressed all the bugs you found. Please let me know if I missed any.

I'll merge after either you check off all of your found items, or you give your thumbs up.

**Comment by amymok** [comment]
@marteki Everything looks good!

**Pull request merged**
