### PR TITLE
Updated format-usd to 1.0.1

### PR DESCRIPTION
**Pull request by mistergone**
This PR updates `format-usd` to `v1.0.1`

Short description explaining the high-level reason for the pull request
## Changes
- Updated version of `format-usd` to `v1.0.1`
- Changed calls to `format-usd` to use new function parameters
## Testing
- Functional and unit tests are all passing, so that part's easy
- All dollar amounts should be formatted in the same way as before.
## Review
- __Be sure to run `npm install` and `gulp` after you switch to the branch, or currency formatting will completely fail!
- @marteki and @higs4281 and @niqjohnson (if you're bored)
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices 
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
### Me, trying to get this very simple change to work:

user-testing

### CODE REVIEW

**Comment by marteki** [comment]
Whee! After some fumbling on my end, works for me in browser and with all tests passing!

Can you run `npm shrinkwrap` on this branch to update and shrinkwrap the new version?

**Comment by marteki** [comment]
:+1:

**Comment by marteki** [comment]
Oh! Changelog update. 😛

**Comment by mistergone** [comment]
`CHANGELOG` updated! If you have a problem with this PR, speak quickly, for I am interested in merging this!

**Comment by higs4281** [comment]
👍 tests pass, looks good

**Comment by mistergone** [comment]
Merging!

merge

**Pull request merged**
