### PR TITLE
Budget national salary

### PR DESCRIPTION
**Pull request by marteki**
This changes the content around the budgeting section if we don't receive program or school salary data.
## Additions
- Added new text where applicable
## Testing

Pull down the branch and run `gulp`. Check out the budgeting area.

[Here's one without salary data at the program level.](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=182111&pid=1412&oid=fa8283b5b7c939a058889f997949efa566c616a6&book=0&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=90175&tran=500&tuit=86975&unsl=2000&wkst=1000)
[Here's one without salary data at the program or school level.](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=480073&pid=2932&oid=fa8283b5b7c939a058889f997949efa566c616a1&book=1500&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=83450&tran=500&tuit=20862&unsl=2000&wkst=1000) The messaging should be different than the link above.
## Review
- @mistergone @higs4281 @amymok 
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [ ] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by higs4281** [comment]
👍 Looks great!

One question: When reverting to nationwide salary, the text says "for all students who attended college" but it should probably be "for students who attended a college similar to yours" since we tailor the stat by predominant degree length.

Alternatively, we could punt like scorecard and deliver the generic value.

**Comment by saintsoup52** [comment]
I think we should punt to the generic value for now because that is what is visible on scorecard and therefore easier to justify.

**Comment by kurzn** [comment]
@saintsoup52 you approved different language yesterday that I specifically asked you about. This matches the approved language. You can log another issue if you like to update that language, which can be addressed post-deployment.

**Comment by saintsoup52** [comment]
The language I approved is the for the generic value... no change here. I was just responding to Bill

**Comment by kurzn** [comment]
@saintsoup52 so is any change needed to data or content or is this approved? Just want to verify.

**Comment by marteki** [comment]
I am merging this PR now. Any data changes from the direction to load the non-generic data (that you approved several months ago) will have to happen later.

**Comment by saintsoup52** [comment]
We should be using the language we approved and the variable that is currently $34,300 like we discussed.

**Comment by kurzn** [comment]
Thanks for the clarification!

**Pull request merged**
