### PR TITLE
Fix for monthly student loan expenses

### PR DESCRIPTION
**Pull request by mistergone**
This is just a very tiny fix to make sure student loan monthly expenses are displayed in the expenses section.
## Changes
- Changed the `data-financial` to the proper variable name
- Changed the expenses calculation to use the `loanMonthly` property
## Testing
- Download, `gulp`, and check out the student loan line of the expenses section
## Review
- @marteki and @niqjohnson 
## Screenshots

screen shot 2016-02-26 at 5 34 39 pm
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices 
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
## Animated GIF

Who's writing functional tests on a Friday evening?

it-crowd-standard-nerds

### CODE REVIEW

**Comment by higs4281** [comment]
:+1: loan showing up where before there was 0

**Comment by marteki** [comment]
LGTM! :smile: :+1:

**Comment by niqjohnson** [comment]
:+1:

**Comment by mistergone** [comment]
@niqjohnson - Commenting on a PR on Friday night? Almost as bad as merging code on a Friday night.

**Pull request merged**
