### PR TITLE
Simple fix for offers with no program ID

### PR DESCRIPTION
**Pull request by mistergone**
This PR is a very simple patch for offers (passed via url querystrings) with no program ID (e.g. `pid=123`).

This PR makes the `fetchProgramData()` function return an response similar to what the `$.ajax()` method would - an array with an Object as the first element. This Object contains one property, `pidNotFound`, which allows us to check if `fetchProgramData()` didn't get a valid program id.

**NOTE:** There will still be problems with this - several things come from program data that are essential, like graduate versus undergraduate, but we can revisit this fix later to try and patch over errors like that if necessary. At this point, I'm not sure at all the best way to patch those possible errors, or the extent of those errors, so I prefer to wait to see what we need to fix.

This PR also addresses incorrect test values in the functional test suite by updating these tests to have the new `prvf` url parameter and test loan values including private loan fees.
## Changes
- Changes `fetchProgramData()` to detect when no `pid` is passed and return a valid response Object.
- Changes to functional testing to reflect updates to private loan fees.
## Testing
- Passes functional and unit tests! I double-checked this time!
## Review
- @marteki and @higs4281 and @amymok 
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
## Animated GIF

There, I fixed it.

fixed-it

### CODE REVIEW

**Comment by mistergone** [comment]
@amymok, @higs4281 - Should I be worried about this test coverage error?

**Comment by marteki** [comment]
Apologies for _also_ missing the broken functional tests. Perils of non-automated testing. 😡  That will be corrected, very very soon. 😈 

Tested with IPED of `215062` (hurrah, hurrah, Penn-syl-va-ni-a). It's now possible to get through the whole page, even if as stated there are some NaNs present. :+1: for merge.

I am curious about this in the PR checklist, though:
screen shot 2016-06-16 at 2 46 43 pm

This _does_ pass all automated tests and can be automatically merged, but _didn't_ have the CHANGELOG updated. Opposite day for PR filling out? 😆

**Comment by higs4281** [comment]
👍 Page works without a program ID specified.

~~an upcoming PR~~ _a commit I pushed by mistake to this branch_ will catch any API calls made without both school and program IDs.

**Comment by mistergone** [comment]
@marteki - Sorry, I don't know why only some of those were checked. I thought, "Oh, this isn't worth putting in the CHANGELOG," but actually, I guess you're right and I should. Here comes that thing!

**Comment by higs4281** [comment]
@amymok could you please look over the view/test changes I pushed to this PR?

**Comment by mistergone** [comment]
@higs4281 - Once you and @amymok are satisfied with the changes you made, feel free to merge this PR!

**Pull request merged**
