### PR TITLE
Quick fix for private loan unit test

### PR DESCRIPTION
**Pull request by mistergone**
The unit test for private loan removal was lame. I buffed it up.
## Changes
- Fix to `publish-update-spec.js` private loan removal test
## Testing
- `npm test` will give you great results!
## Review
- @marteki @niqjohnson 
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices 
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
## Special Thanks

@niqjohnson for pointing out the error!

### CODE REVIEW

**Comment by marteki** [comment]
All unit tests passing!

:+1:

**Comment by marteki** [comment]
Oh, but you have a console.log() in there that you might not want to keep...

**Comment by mistergone** [comment]
@marteki Gargh! Personal shame removed.

**Comment by marteki** [comment]
As someone who frequently forgets to remove her console.log() statements, I intended no shame. More like "hey, he does the same thing I do, too!"

**Comment by mistergone** [comment]
No, the shame is entirely personal (meaning self-originating and self-directed). :wink: :disappointed: :crying_cat_face: :rocket: :octopus:

**Comment by niqjohnson** [comment]
:+1: 

All unit tests passing for me, too

**Comment by mistergone** [comment]
Greeeeeat! Merging!

tony-the-tiger

**Pull request merged**
