### PR TITLE
Api

### PR DESCRIPTION
**Pull request by higs4281**
This makes model and api adjustments for our first deployment to build.
## Additions
- no_hastack settings file to allow efficient data loading
- new model fields to handle API data
- fix tests to match API script changes
## Changes
- API scripts updated with new fields and harvesting routine
- switches to python3-compliant print statements, a SAG recommendation
## Testing

After importing, update the database for new model fields with:

``` bash
./manage.py migrate paying_for_college
```

If using UnityBox, this needs to be run from inside the vagrant machine:

``` bash
vagrant ssh
workon cfpb_django
cd /var/www/django/cfpb
./manage.py migrate paying_for_college
sudo service httpd restart
```
## Review

You can ignore the migration files.
- @ascott1 @marteki @niqjohnson

### CODE REVIEW

**Comment by niqjohnson** [comment]
Migrations seemed to run fine and everything seems to work for me in UnityBox and standalone. :+1:

**Comment by marteki** [comment]
Fast migrations that ran without errors. Working in both standalone and UnityBox for me as well. :+1:

**Comment by ascott1** [comment]
Seems a-ok to me too. @higs4281 do you know why Travis is failing though?

**Comment by higs4281** [comment]
@ascott1 weird. I pushed 191e060 to fix it, and I got an email saying it passed. 

i was trying to make the API scripts python3 compliant, and our creaky python 2.6 (still used on servers) takes special treatment when doing so.

**Pull request merged**
