### PR TITLE
Content updates

### PR DESCRIPTION
**Pull request by niqjohnson**
Update design and content to match the latest small-screen mockup
## Changes
- Update content to match what was submitted for pre-clearance
- Update design to match latest mockup
- Change to more semantic line breaks in the HTML for easier editing (sorry about the diff on that one…)
## Testing
- This will only look right at small screen sizes. To test in standalone mode, pull in the `content-updates` branch, run `gulp`, then run `./manage.py runserver` from your virtual environment. The page will be at `http://localhost:8000/paying-for-college/demo/`. Fire up Chrome's device emulator (or shrink your browser) and check it out on a phone-sized screen.
## Review
- @ascott1
- @marteki 
- @kurzn and/or @caheberer: Are the design and content in this version correct enough to move on to starting work on the large screen? Details don't have to be perfect yet, but I want to make sure I'm not missing any major sections or content.
## Screenshots

Get ready to scrooooooooooll!

content-updates-screenshot
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] Visually tested in supported browsers and devices

### CODE REVIEW

**Comment by niqjohnson** [comment]
I was holding off on making the "adjusting some of the offer amounts" link work until we started work on the interactions. I wasn't sure if that was meant to be a regular anchor link or a smooth scroll up to the correct section of the page.

**Comment by marteki** [comment]
Matches up with the latest content doc I see on our shared drive. 
Works in UnityBox for me, on Mac Chrome and the latest Android Chrome Beta. :raised_hands: 

~~I commented in the diff with a question about one of the placeholder links. Not something that I'd hold this PR up for, though.~~ Didn't see your response in the timeline. That explanation makes sense to me for merging. :+1:

**Comment by higs4281** [comment]
:+1: looking great. One note:

> "We have sent an email to your school notifying them ..."

As noted before, we're hoping to avoid email, so we need to say

> "We have notified your school ..."

**Comment by ascott1** [comment]
This is working great for me. :+1:

**Comment by kurzn** [comment]
On a quick scan, content looks kosher to me.

**Pull request merged**
