### PR TITLE
Fixes, Round 3

### PR DESCRIPTION
**Pull request by mistergone**
This PR is big and unwieldy, and for that I apologize. I let the scope creep out into too many issues.

This PR should fix the following bugs:
- New private loans default to 7.9% interest
- Dynamic content trigged by a positive or negative amount left to pay should appear
- Default rate should appear properly, with a program value of "None" reverting to the school value
- The "Select an option" option for the program length has been eliminated
- Half-year program lengths should no longer break things
- Program lengths of 6 months should work properly
- Grad and Default rate graphs should properly display "This School" or "This Program" depending on data source
- If program salary data is not available, school salary data should be used
- Error notifications for Direct loans should display a new, more correct error message
## Additions
- Added some properties to various models to track sources and differentiate values such as salary more completely.
- Added code to properly update content of graphs based on source
## Testing
- Passes existing unit tests
## Review
- @marteki @higs4281 
## Checklist
- [ ] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by marteki** [comment]
Tested across three different example aid offers: certificate, undergraduate, and graduate.

Moved up because folks were having issues finding the links I used to test:
- [Certificate](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=222938&pid=3266&oid=fa8283b5b7c939a058889f997949efa566c616a7&book=800&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=24224&tran=500&tuit=23424&unsl=2000&wkst=1000)
- [Undergrad](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=182111&pid=1412&oid=fa8283b5b7c939a058889f997949efa566c616a6&book=0&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=90175&tran=500&tuit=86975&unsl=2000&wkst=1000)
- [Graduate](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=145770&pid=1380&oid=9e0280139f3238cbc9702c7b0d62e5c238a835a0&book=650&gib=3000&gpl=1000&hous=3000&insi=4.55&insl=3000&inst=36&mta=3000&othg=100&othr=500&parl=10000&pelg=1500&perl=3000&ppl=1000&prvl=3000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=62795&tran=500&tuit=60895&unsl=2000&wkst=3000)

Confirmed working across all:
- New private loans default to 7.9% interest
- The "Select an option" option for the program length has been eliminated
- Half-year program lengths should no longer break things
- Program lengths of 6 months should work properly
- Grad and Default rate graphs should properly display "This School" or "This Program" depending on data source
- If program salary data is not available, school salary data should be used

Tweaks needed:
- **Dynamic content trigged by a positive or negative amount left to pay should appear**
  
  Working great! Could you also remove the negative sign for over-borrowing, as described in internal issue 154?
- **Default rate should appear properly, with a program value of "None" reverting to the school value**
  
  Something is off here. Maybe not being treated as a percentage?
  
  screen shot 2016-08-02 at 12 15 44 pm

Further discussion internally, especially by @kurzn and @saintsoup52:
- **Error notifications for Direct loans should display a new, more correct error message**
  
  This leads to the following potentially being presented to a certificate or undergrad student on the same page:
  
  screen shot 2016-08-02 at 12 19 22 pm
  
  screen shot 2016-08-02 at 12 19 35 pm
  
  While a graduate student who is only eligible for unsubsidized loans gets the following message:
  
  screen shot 2016-08-02 at 12 20 25 pm

Links used to test:
- [Certificate](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=222938&pid=3266&oid=fa8283b5b7c939a058889f997949efa566c616a7&book=800&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=24224&tran=500&tuit=23424&unsl=2000&wkst=1000)
- [Undergrad](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=182111&pid=1412&oid=fa8283b5b7c939a058889f997949efa566c616a6&book=0&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=90175&tran=500&tuit=86975&unsl=2000&wkst=1000)
- [Graduate](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=145770&pid=1380&oid=9e0280139f3238cbc9702c7b0d62e5c238a835a0&book=650&gib=3000&gpl=1000&hous=3000&insi=4.55&insl=3000&inst=36&mta=3000&othg=100&othr=500&parl=10000&pelg=1500&perl=3000&ppl=1000&prvl=3000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=62795&tran=500&tuit=60895&unsl=2000&wkst=3000)

**Comment by mistergone** [comment]
I can't currently replicate the "1730%" error. If anyone else can, please let me know!

**Comment by marteki** [comment]
Additional tweak: per the approved Illustrator file, the casing in the graphs for program/school should be sentence case. (In other words, "This program" or "This school".)

screen shot 2016-08-02 at 1 30 55 pm

**Comment by mistergone** [comment]
> Additional tweak: per the approved Illustrator file, the casing in the graphs for program/school should be sentence case. (In other words, "This program" or "This school".)

Easy fix. I'm on it!

**Comment by marteki** [comment]
Both recent commits for quick fixes working for me. If:
- someone else reviews this and can't replicate the high percentages, and
- @kurzn or @saintsoup52 confirms that the direct loan error messaging is supposed to work that way,

then 👍  from me.

**Comment by saintsoup52** [comment]
@marteki Those loan error messages look fine to me. Thank you for double checking.

**Comment by kurzn** [comment]
For graduate programs, the only warning that should appear is "The maximum that can be borrowed per year is XX" where X = $20,500 right now. 

There is never a combined sub/unsub warning for grad students. 

For undergraduate students: 

If an amount is over for EITHER sub or unsub by itself, the error should be

"The maximum that can be borrowed per year is $XX" - original error messaging from the GH issue

The only time an undergrad sees the NEW error message of: 
"The maximum combined subsidized and unsubsidized loans that can be borrowed per year is XX" is when they enter an amount in either sub or unsub that results in a TOTAL over that XX amount. 

I want to double check with @saintsoup52 if this is even a use case.

**Comment by saintsoup52** [comment]
@kurzn is correct... and after rethinking what I just wrote... what @kurzn  is correct and what I wrote before is incorrect

**Comment by mistergone** [comment]
I've pushed an additional commit which should fix the content for Direct Unsubsidized over cap errors, both in the case of graduate and undergrad programs.

**Comment by marteki** [comment]
```
-          directUnsubsidized: 'directUnsubsidizedIndepMax',
-          directUnsubsidizedGrad: 'directUnsubsidizedIndepMax'
+          directUnsubsidized: 'unsubsidizedCapIndepYearOne',
+          directUnsubsidizedGrad: 'unsubsidizedCapGrad'
```

Cool, you found the variables I had remaining questions about! I was just about to ping you to figure out what they were.

Latest commit fixes the error messaging to what we discussed after scrum. :+1: assuming that the graph percentage problems were just my machine.

**Comment by higs4281** [comment]
## Tests
- [x] New private loans show 7.9% interest  
- [x] Dynamic content for pos and neg totals
- [x] the tool reverts to showing the school default rate [when program default_rate is missing](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=436094&pid=2575&oid=fa8283b5b7c939a058889f997949efa566c616a7&book=800&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=24224&tran=500&tuit=23424&unsl=2000&wkst=1000#info-right), but **shouldn't we hide the link** to "See the loan default rates for the entire school" -- Same for grad rates that default to school.

whole_school_default_link
- There are no schools in our database that have programs attached AND have no default rate, so we can't test that condition.
- [x] 'select an option' eliminated
- [x] half-year options aren't breaking things
- [x] 6-month length works
- [x] "this school" and "this program" [content is right](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=436094&pid=2575&oid=fa8283b5b7c939a058889f997949efa566c616a7&book=800&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=24224&tran=500&tuit=23424&unsl=2000&wkst=1000#info-right), **except in graph intro**, where we say "students from this program":

this_school
- [x] missing grad info [defaults correctly](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=452090&pid=2266&oid=fa8283b5b7c939a058889f997949efa566c616a7&book=800&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=24224&tran=500&tuit=23424&unsl=2000&wkst=1000#info-right), but if both program and school are blank, shouldn't we hide the graph?

blank_grad_graph
- salary [reverts to school](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=173984&pid=875&oid=fa8283b5b7c939a058889f997949efa566c616a7&book=800&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=24224&tran=500&tuit=23424&unsl=2000&wkst=1000#info-right) if program salary missing (all program salary data currently blank), but the paragraph misstates the source -- says the salary is for "students graduating from your program"

your_program
- [x] not seeing the "1730%" error

**Comment by mistergone** [comment]
@higs4281 - We do need to display "No Data" errors, but that feature is Not Yet Implemented.

**Comment by mistergone** [comment]
@higs4281 points out several content issues that require work, but I don't think they should hold up this PR. Does anyone else have any opinions on that?

**Comment by higs4281** [comment]
👍 I don't think it should hold this PR

**Comment by marteki** [comment]
I've already flagged some of them as a new issue today on the internal repo. 😄

**Comment by mistergone** [comment]
Merging!

**Pull request merged**
