### PR TITLE
remove duplicate test; fix standalone js so we can see a saved worksheet

### PR DESCRIPTION
**Pull request by higs4281**
## Additions
- worksheet.json fixture for testing a saved worksheet
## Removals
- duplicate view test
## Changes
- fixed url in standalone js so we can see a saved worksheet
- updated comments in test_views.py with correct urls
## Review
- @ascott @niqjohnson @marteki 
## Testing (standalone or UnityBox)
- load the test worksheet with 

``` bash
./manage.py loaddata worksheet.json
```
- check this saved-worksheet url (you may need to refresh it once):

```
/paying-for-college/understanding-financial-aid-offers/#00470019-e077-4fc3-9dbb-4a595fe976e6
```

You should see a worksheet for ITT Technical Institute–Tallahassee:

worksheet_test

### CODE REVIEW

**Comment by niqjohnson** [comment]
I'm having trouble getting this working in standalone or UnityBox. In standalone, `./manage.py loaddata worksheet.json` works OK (1 fixture loaded...), but visiting the URL gives me this error in my terminal:

```
POST /paying-for-college/understanding-financial-aid-offers/api/worksheet/00470019-e077-4fc3-9dbb-4a595fe976e6.json HTTP/1.1" 403 2282
```

Chrome's web inspector gives a similar error:

```
POST http://localhost:8000/paying-for-college/understanding-financial-aid-offers/api/worksheet/00470019-e077-4fc3-9dbb-4a595fe976e6.json 403 (FORBIDDEN)
```

Chrome gives the same error in UnityBox.

**Comment by higs4281** [comment]
rats. it's working in both places for me. 
i don't think we should spend time chasing this down, as we're not currently planning to store worksheets, and this is probably a local issue. we can revisit if necessary once we get on build.

**Comment by ascott** [comment]
@higs4281 you've got the wrong @ascott in your PR. looks like you are looking for @ascott1 :)

**Comment by higs4281** [comment]
@ascott sorry about that, and thanks for the note!

**Pull request merged**
