### PR TITLE
Update about page to new design standards

### PR DESCRIPTION
**Pull request by niqjohnson**
Updates the "about this tool" page to new design standards (specifically, the V1 "learn" page style)
## Additions
- A few `cf-enhancements` styles
## Changes
- Markup of `technote.html` to use standard Capital Framework classes and the updated template elements from `worksheet.html`
## Testing
- To test, pull in the `about-page` branch and run `gulp`. Fire up the app in standalone or UnityBox as normal. Follow the "Get details about how this tool works" link.
- Besides having an updated style, the about page should now be responsive, too
## Review
- @marteki and/or @mistergone and/or @higs4281 
## To do
- Add new content to the page when the content is ready
- <strike>Fix a JS error on the page (I'll open a separate issue for this)</strike>
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] Visually tested in supported browsers and devices

### CODE REVIEW

**Comment by higs4281** [comment]
:+1: a great improvement, and responsive parts are working.

You can fix the failing constants call by adding an attribute to main:

```
  <main data-context="{{url_root}}">
```

**Comment by niqjohnson** [comment]
@higs4281: Thanks! Pushed that fix, so now the page should be error free.

**Comment by higs4281** [comment]
:tophat: errors be gone!

**Comment by marteki** [comment]
Huzzah! The sidebar has a placeholder heading and no content, but I assume that will be fixed with the new content.

Working on standalone, with no errors now. :+1:

**Pull request merged**
