### PR TITLE
Fix for functional tests

### PR DESCRIPTION
**Pull request by mistergone**
This is a small PR that fixes some functional tests.

**Values were derived from the Official College Cost Comparison Spreadsheet<sup>TM</sup>!**

Short description explaining the high-level reason for the pull request
## Changes
- Fixes functional tests
## Testing
- 6 tests failing (for Step 2), as expected
## Review
- @marteki @niqjohnson 
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices 
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by marteki** [comment]
:+1:

**Comment by niqjohnson** [comment]
:+1:

**Comment by mistergone** [comment]
Mergining!

**Comment by mistergone** [comment]
Fixed a merge conflict, values for total debt match the spreadsheet!

Merging this now.

**Comment by marteki** [comment]
w00t!

**Pull request merged**
