### PR TITLE
Build out and populate the About This Tool page

### PR DESCRIPTION
**Pull request by marteki**
This enables dynamic technical notes through the About This Tool page. It also makes loan origination fees on the worksheet dynamic from the API.
## Additions
- Add technical notes on the About This Tool page
## Changes
- Make Direct and Grad Plus loan origination fees dynamic from the API
## Testing

Pull down the branch, and load up a sample URL. Click the link to go to the About This Tool page. All content should match the cleared Word doc on our internal drive, all constants should match our API values, and there should be no errors or NaNs displayed on the page.
- All unit tests should pass.
- All NPM security tests should pass.
- The bulk of our functional tests are still failing, but you can test the two new ones I wrote for this PR by changing the first word of lines 377 and 386 in `dd-functional-settlement-spec.js` to be "fit" instead of "it", and then running: `protractor test/functional/conf.js --specs test/functional/dd-functional-settlement-spec.js`
## Review
- @mistergone @higs4281 @amymok
## Screenshots

Top of the page

screen shot 2016-08-03 at 4 42 19 pm

Example of the values being populated dynamically

screen shot 2016-08-03 at 4 42 37 pm
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [ ] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by higs4281** [comment]
A thing of beauty.

A few nits: 
- Unfrozen journalist says use single quotes in an h1
- "federal" is capitalized once and lowercase elsewhere. Should be lower everywhere.
- Subsidized loan fee shows as  "1.1% of the total loan amount". shouldn't that be "1.01%?
- Grad Plus loan fee shows as "4.3% of the total loan amount" -- shouldn't that be "1.043%?"

Typos:
- "These repayment planes have lower ..."
- "Benefits includes"

**Comment by marteki** [comment]
> Subsidized loan fee shows as "1.1% of the total loan amount". shouldn't that be "1.01%?
> Grad Plus loan fee shows as "4.3% of the total loan amount" -- shouldn't that be "1.043%?

Sadly, no. This is most of why this PR took so long to release.

The API constants deliver:

```
"DLOriginationFee": "0.01011"
"plusOriginationFee": "0.01043"
```

From the cleared content doc for subsidized loans:

screen shot 2016-08-03 at 9 34 14 pm

And for Grad Plus:

screen shot 2016-08-03 at 9 34 33 pm

And finally, from the [Department of Education's website on loans](https://studentaid.ed.gov/sa/types/loans/interest-rates#fees):

screen shot 2016-08-03 at 9 37 39 pm

We talked about this a bit back in July, on internal issue 135. I've never been able to see the change in the loan rates that you said you made, and built a Javascript function in order to get the API origination fee values to something that is closer to the actual loan fee amounts. But based, on the numbers (and possibly because of rounding?), it still doesn't match the values released by the Dept of Ed. 😞

**Comment by marteki** [comment]
From Bill:

> Unfrozen journalist says use single quotes in an h1

@kurzn, I'm seeing conflicting or ambiguous items in our consumer-facing editorial style guide and the related editorial working group discussions about what to do here. Either we should use double quotes here around the tool name, or no quotes at all. Which should it be?

**Comment by higs4281** [comment]
> "DLOriginationFee": "0.01011"
>   "plusOriginationFee": "0.01043"

@saintsoup52 so are these values wrong?

**Comment by saintsoup52** [comment]
This is a legacy issue with the way we had loans fees in the constant section.

The PLUS loan fee is 4% but we had it as 1.04 in the constants file to make the equations work.

Then we changed constant by taking out the 1 so it should only say 0.04.

But what I think happened is that someone 1.04 divided by 100 and got .0104 which is incorrect.

Hope that makes sense.

**Comment by mistergone** [comment]
I think `student-debt-calc` also needs to be updated to expect origination fees expressed as decimals less than 1 (instead of as coefficients greater than 1). This is a quick fix in `student-debt-calc` which will bring us up to version 2.6.0!

**EDIT**: Oh, I keep forgetting this. We no longer include federal loan fees in our calculations because we found out the fees are taken from the principal, not added to it. So uh... `student-debt-calc` ignores those fees altogether.

**Comment by marteki** [comment]
Things remaining on this PR:
- [ ] Clarification from @kurzn on use of single/double/no quotes in an h1
- [ ] Loan origination fees. I propose that this PR be merged, with a fast follower fix after the constants API is updated with correct values. What say y'all?

**Comment by higs4281** [comment]
👍 My constants questions should not hold up this PR
Also, you should ignore unfrozen journalist at will; I just like our headlines to look more like NYT than buzzfeed.

I'll fix the 1.04/0.04 problem for PLUS loan fee

**Comment by mistergone** [comment]
Aside from what's already pointed out in this thread, this PR looks good to me! 👍

**Comment by marteki** [comment]
Merging, and creating followup issues internally for the remaining items.

**Pull request merged**
