### PR TITLE
Add responsive header and footer to standalone Django template

### PR DESCRIPTION
**Pull request by ascott1**
This adds a responsive version of the nemo header and footer (ala Owning a Home) when running the app in standalone mode.

Feel free to :-1: if we don't want to merge the demo template into `master`.
## Screenshot

screen shot 2015-11-24 at 12 39 11 pm
## Review
- @niqjohnson 
- @higs4281

### CODE REVIEW

**Comment by higs4281** [comment]
:+1: works great in standalone. i vote to merge. we can adjust unitybox to match.

**Comment by niqjohnson** [comment]
Looking awesome! In `paying_for_college/templates/just-a-demo.html`, can we override the viewport meta tag like so?

``` python
{% block page_viewport %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock %}
```

That was the only way I could get the responsiveness to happen in Chrome's device emulator (it worked fine shrinking down the window's width, though).

**Comment by ascott1** [comment]
Good catch @niqjohnson! I updated the template and pushed it. Thanks!

**Comment by niqjohnson** [comment]
:+1: Works for me in Chrome and Chrome's device emulator.

**Comment by ascott1** [comment]
:tada:

**Pull request merged**
