### PR TITLE
Fix to correct monthly loan payment and lifetime loan payment values

### PR DESCRIPTION
**Pull request by mistergone**
The numbers for "Total cost of repayment with interest" are supposed to represent the total cost of the loans over the repayment period. After a few updates to `student-debt-calc`, I have the values working and live in `college-costs`.
## Additions
- Lifetime loan cost is rounded after calculation, before the view is updated.
## Changes
- Changed the DOM so that the correct variable (`loanLifetime`) is used for total cost of repayment.
- Updated version of `student-debt-calc`
- Updated functional tests to sleep 750 ms (up from 600 ms). This seemed to help with some false positives (or negatives?) where functional tests would fail occasionally for no apparent reason. I assume sometimes the sleep wasn't enough for the calculations to be done and the view updated.
- Updated functional tests to check for correct lifetime loan values.
## Testing
- Pull it down, be sure to run `npm install` to get updates to `student-debt-calc`, and then feel free to try it and run functional tests.
- Six functional tests for Step 2 are failing (as expected)
## Review
- @niqjohnson @marteki @higs4281 
## Checklist
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [ ] Passes all existing automated tests
- [ ] New functions include new tests
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged
- [ ] Visually tested in supported browsers and devices 
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
## Animated GIF

Putting out fires is like...

moss-fire

### CODE REVIEW

**Comment by marteki** [comment]
Whee, `student-debt-calc` at 2.2.2! :smile: 

I'm getting a seventh functional test failure:

> Failures:
> 1) A dynamic financial aid disclosure that's required by settlement should properly update when the Federal Pell Grants are modified above the Federal limits
>   Message:
>     Expected '15830' to equal '15915'.
>   Message:
>     Expected '27796' to equal '27711'.
>   Message:
>     Expected '-4704' to equal '-4789'.

**Comment by mistergone** [comment]
Those failed tests are because the Pell grant max is now set at $5,815 (the limit starting on July 1). So  @higs4281 updated that at some point, and loading `collegedata.json` should make those tests work.

**Comment by marteki** [comment]
Ha, of course! Duh. :laughing: 

LGTM! :+1:

**Comment by niqjohnson** [comment]
:+1: 

I'm seeing one test fail, `publish updates to the model drops private Loans from privateLoanMulti`, but that can be fixed separately.

**Comment by mistergone** [comment]
Merging, then addressing that test.

**Pull request merged**
