### PR TITLE
Tweaks for "live update" of input fields

### PR DESCRIPTION
**Pull request by mistergone**
This PR is low on code, but high on effect. See "Changes" below.
## Changes
- App **does not** update the current field being edited, although it does use its value (and still enforces limits, etc, in the math, even if the field does not reflect those limits)
- When user tabs from an input field, that field is instantly updated and formatted. (This was supposed to be the existing functionality, but it wasn't working.)
## Testing
- Pull it down, `gulp` it, and try to edit inputs and tab around and whatnot. 
- All functional tests, unit tests are passing
## Review
- @marteki and @niqjohnson and @higs4281 
## Todos
- Proper error handling for when the user goes over limits, etc.
## Checklist
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [ ] Passes all existing automated tests
- [ ] New functions include new tests
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged
- [ ] Visually tested in supported browsers and devices 
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
## Animated GIF

The keyup interactions are now...

pretty-pretty-good

### CODE REVIEW

**Comment by niqjohnson** [comment]
:+1: 

Working great for me on Chrome/Mac, Safari/Mac, and Safari/iPhone.

**Comment by higs4281** [comment]
:+1: works for me as well

**Comment by marteki** [comment]
And another :+1: from me, in standalone and Unitybox. Let's get this in front of people!

**Comment by mistergone** [comment]
Merging!

**Pull request merged**
