### PR TITLE
Functional tests for evaluating an offer

### PR DESCRIPTION
**Pull request by marteki**
More functional tests. This time for evaluating an offer.
## Additions
- Added new tests for estimated monthly expenses (with added IDs to the worksheet).
- Added commented-out placeholder tests for incoming JS functions for estimated expenses
## Testing

Pull in the `functional-tests` branch and run `npm install`.

Make sure you have webdriver and protractor all set up:

``` bash
npm install -g webdriver-manager protractor
webdriver-manager update --standalone
```

Run `gulp`, and load the standalone server using `python manage.py runserver`. 

To run the tests:

``` bash
# Open a new terminal tab, and start webdriver:
webdriver-manager start
# Open a third tab, and run:
protractor test/functional/conf.js
```

You should eventually see something like the following:

```
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started
................................


32 specs, 0 failures
Finished in 55.862 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed
```
## Review
- Some combination of: @mistergone @higs4281 @niqjohnson @ascott1 or any other interested parties
## To do next
- Work with @mistergone on creating tests for multiple private loans
## Checklist
- [X] Changes are limited to a single goal (no scope creep)
- [X] Code can be automatically merged (no conflicts)
- [X] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [ ] Passes all existing automated tests
- [X] Placeholder code is flagged
- [X] Visually tested in supported browsers and devices

### CODE REVIEW

**Comment by niqjohnson** [comment]
All the tests pass for me when I run them without updating this branch. If I merge the latest changes to `master` in, though, all the calculation tests fail (thanks to the fields now getting populated from the URL in `master`).

If the plan is to merge these new tests first and then refactor the tests to accommodate the pre-population, then I say :+1:

**Comment by marteki** [comment]
The dangers of advancement and improvement. :smile: 

I can make a quick fix this afternoon. Please hold. Your review is important to us.

**Comment by marteki** [comment]
Code refactored to deal with the auto-population.

What do folks think about making sure that we rewrite and run their own functional tests when we submit changes to the FE code? There's been some regression in the code and an increase in failing tests, mostly due to this documented bug (https://github.com/cfpb/college-costs/issues/71), the private loan changes, and also in the monthly expenses section.

In the interest of moving forward and getting to other functional test PRs, it means that the current expected status of our tests is something like:

> 31 specs, 17 failures
> Finished in 49.931 seconds

**Comment by marteki** [comment]
Running the code again:

> 31 specs, 24 failures
> Finished in 45.952 seconds

**Comment by mistergone** [comment]
I don't think "passing all functional tests" is _necessarily_ a good mark for a PR. Sometimes, functional tests should exist and fail as a reminder that we have work to do. However, I think a PR should contain information about which functional tests are failing and "why" (maybe we know how to fix it, but we can't yet, or maybe we haven't decided how to fix it yet, or maybe we don't know).

Basically, there might be perfectly cromulent reason to file a PR with failing functional tests, especially "because otherwise the scope of this PR would be enormous." Ideally, we should not be breaking old tests when we write new code, but... well, sometimes that happens. And if one of us makes a PR and another one of us doesn't like that 10 previously working tests are now broken, then the PR is exactly the place to state that. Not every PR needs to be merged. That's why we all should comment on PRs. :smile: 

Note that, in my mind, this only applies to functional tests. Unit tests should be passing when you file a PR.

**Comment by marteki** [comment]
> I don't think "passing all functional tests" is necessarily a good mark for a PR. Sometimes, functional tests should exist and fail as a reminder that we have work to do. However, I think a PR should contain information about which functional tests are failing and "why" (maybe we know how to fix it, but we can't yet, or maybe we haven't decided how to fix it yet, or maybe we don't know).

Okay, I can get behind that. That builds in the expectation that functional tests were run before the PR was put up, even if they're failing. And that the new stuff is also being tested, or will be very soon.

(The concept  as a whole might be something to take up at our internal FEWD meetings, since it goes against one of the items in our development checklist ["Passes all existing automated tests"] and might be against the stated goal that those of us who are acting as devs are supposed to strive for at the Bureau. But that's a discussion for a much larger group, at another time, and isn't a main point for this PR.)

> Basically, there might be perfectly cromulent reason to file a PR with failing functional tests, especially "because otherwise the scope of this PR would be enormous." Ideally, we should not be breaking old tests when we write new code, but... well, sometimes that happens. And if one of us makes a PR and another one of us doesn't like that 10 previously working tests are now broken, then the PR is exactly the place to state that. Not every PR needs to be merged. That's why we all should comment on PRs. :smile:

:smile: I think we're in total agreement on this point.

**Comment by niqjohnson** [comment]
:+1:

**Comment by mistergone** [comment]
> The concept as a whole might be something to take up at our internal FEWD meetings, since it goes against one of the items in our development checklist ["Passes all existing automated tests"]

I'm comfortable rocking the boat on this. I am comfortable rocking the boat on a lot of things. :point_right: :boat:

**Comment by marteki** [comment]
Merging, and we can improve as we go from here.

**Pull request merged**
