### PR TITLE
Add verify offer section

### PR DESCRIPTION
**Pull request by niqjohnson**
Add the static "verify this is my offer" section. This PR does not support pre-populating the school or program information in that section (that will come later).
## Additions
- Add section's HTML in `just-a-demo.html`
- Add section's CSS in `disclosures.less` and `cf-enhancements.less`
## Removals
- Remove sample styles form `main.less`
## Changes
- Modify the student debt calculator demo's HTML and CSS for easier removal later
## Testing
- This will only work at small screen sizes in the standalone version. To test, pull in the `verify-offer` branch, run `gulp`, then run `./manage.py runserver`from your virtual environment. The page will be at `http://localhost:8000/paying-for-college/demo/`. Fire up Chrome's device emulator (or shrink your browser) and check it out on a phone-sized screen.
- I've tested this in Mac Chrome and Mac Safari.
## Review
- @ascott1: is the HTML and LESS up to standards?
- @caheberer: does this look close to your mockup?
- @marteki
## Screenshots

verify-info
## Todos
- Test in all supported browsers and devices
- Remove student debt calculator demo when it's no longer needed on the page
- Move the HTML from the demo template into the real one when that template is ready
## Checklist
- [X] Changes are limited to a single goal (no scope creep)
- [X] Code can be automatically merged (no conflicts)
- [X] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [X] Passes all existing automated tests

### CODE REVIEW

**Comment by higs4281** [comment]
:+1: looking great!

**Comment by ascott1** [comment]
Double :+1: Nice work @niqjohnson!

**Comment by marteki** [comment]
Super duper nice, Niq. :+1:

**Comment by niqjohnson** [comment]
Updated content and design to match the latest mockup

## Additions
- Add a `list__flush-left` class for lists with no left padding

## Changes
- Update content

## Testing
- Same as in the original PR note

## Review
- @ascott1: Mind checking the new HTML and LESS one more time?

## Screenshots

verify-offer

**Comment by higs4281** [comment]
Can you take out the empty nemo style block?

{% block nemo_styles %}
{% endblock %}

that wipes out the nemo_style block delivered by the django_cfgov_common base template in UnityBox and breaks the header.

**Comment by ascott1** [comment]
@higs4281 I think in this case we want to wipe out those styles, as we're building them ourselves. Having that block empty means that we can apply our own styles to the existing header and footer and use Capital Framework.

@niqjohnson I read through the markup and Less and everything looks good to me, but let's clarify @higs4281 request above in case I'm missing something. Otherwsie :+1:

**Comment by higs4281** [comment]
if we're intending to exclude that import, go forth! :+1:

**Pull request merged**
