### PR TITLE
Fixes "odd and wonky" keyboard bug, adds JSDoc comments

### PR DESCRIPTION
**Pull request by mistergone**
Fixes "odd and wonky" keyboard bug, adds JSDoc comments. This is mostly just a quick PR to help encourage us by example to document our functions using the JSDoc format.
# Fixes
- "Odd and wonky" keyboard bug by recalculating and updating fields immediately on `focusout` event from a relevant `INPUT` field.
# Adds
- JSDoc comments
# Changes
- Refactors `updateView` slightly for clarity and readability
## Testing
- Passing Step 1 tests, failing 6 Step 2 tests, as one might expect given that this PR doesn't change much.
## Review
- @marteki and @niqjohnson and @higs4281 
## Todos
- Oh, darn. We should fix those Step 2 functional test failures.
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices 
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
## Animated GIF

byrne-bigsuit

### CODE REVIEW

**Comment by niqjohnson** [comment]
Love the comments, love the fix to the oddest and wonkiest keyboard bugs!

`gulp lint` returns one error:

```
src/disclosures/js/utils/query-handler.js
  47:3   error    Missing JSDoc @returns for function                              valid-jsdoc
```

Otherwise :+1: 

(I'll open a new issue to rethink doing anything with the input values on keyup so it doesn't hold up this PR.)

**Comment by mistergone** [comment]
@niqjohnson - Any changes we make will probably use the same basic structure, codewise, so yeah, let's discuss, but no reason to worry about what that code will look like yet.

**Comment by mistergone** [comment]
Added a quick JSDoc update to fix the error @niqjohnson found!

**Comment by higs4281** [comment]
:+1: i get 6 test fails as expected;

one nit: rather than flopping doc comments between "function which" and "function that," I'd stick with the proper "function that" usage.

**Comment by mistergone** [comment]
@higs4281 Oh nards, you're coming at me for prepositions? :wink:

**Comment by higs4281** [comment]
always

**Comment by mistergone** [comment]
Merging this!

**Pull request merged**
