### PR TITLE
Patch for Tuition Payment Plans

### PR DESCRIPTION
**Pull request by mistergone**
Quick patch for TPPs
## Changes
- Changed how TPPs are added to totals
## Review
- @marteki @higs4281 - Pull it down, gulp, check it out
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by marteki** [comment]
Tested using a [sample certificate program](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=222938&pid=3266&oid=fa8283b5b7c939a058889f997949efa566c616a7&book=800&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=24224&tran=500&tuit=23424&unsl=2000&wkst=1000). Works correctly for every program length except six months:

screen shot 2016-08-05 at 5 52 44 pm

**Comment by mistergone** [comment]
@marteki - The 6-month total is unrelated. That is, as I feared, `student-debt-calc` incorrectly calculating the total costs of 6-month programs. I don't have a fix for that because I don't have the math for that.

**Comment by saintsoup52** [comment]
Sorry @mistergone I see the issue now...

Thankfully this is not too complicated... in the student debt calc we should just say that if program length is less then 1 then program length = 1. Then all the equations will just work.

**Comment by higs4281** [comment]
👍

**Comment by mistergone** [comment]
I just pushed a patch that updates `student-debt-calc` to 2.5.10, which will minimize `programLength` to at least 1 when calculating debt totals (which in turn affects lifetime total and monthly payments).

**Comment by higs4281** [comment]
👍 works as expected for 6-month program

**Comment by marteki** [comment]
:+1:

**Comment by mistergone** [comment]
Merging!

**Pull request merged**
