### PR TITLE
update repayment to reflect new income base repayment rules

### PR DESCRIPTION
**Pull request by ascott1**
This includes the updates to the repayment tool that were made in the old internal project repo.
## Review
- @higs4281 

I know things are set up differently between the two repos, so let me know if I mangled anything when transferring this over here.

### CODE REVIEW

**Comment by higs4281** [comment]
Content changes look great, but I think we'll want to stick with this static pathing:
  `{% static "paying_for_college/repaystudentdebt/ ..." %}`
That will be consistent with the rest of the app and newer apps on cfgov.
That pathing should make use of static assets restored in [PR47](https://github.com/cfpb/college-costs/pull/47)

**Comment by ascott1** [comment]
Good catch @higs4281. That was unintentional when copying things between the old repo and here. I'll push a fix today.

**Comment by ascott1** [comment]
@higs4281 I just pushed an update that should correct my static path error. Thanks again for catching!

**Comment by higs4281** [comment]
:+1:

**Comment by ascott1** [comment]
PUSH THE BUTTON

**Pull request merged**
