### PR TITLE
Fixes Grad PLUS loan calculations, other errors

### PR DESCRIPTION
**Pull request by mistergone**
This PR updates `student-debt-calc` to version 2.6.0, which fixes Grad PLUS loan limit calculations. It also addresses an odd calculation error caused by inconsistent variable use in `student-debt-calc`.
## Changes
- updates `student-debt-calc` to 2.6.0
- updates `browser-sync` to 2.14.0 (fixes a vulnerability)
## Testing
- Passes unit tests!
## Review
- @marteki @higs4281 - pull it down, `npm install`, `gulp`, and try it out!
- [Here's a (localhost) link where Grad PLUS should be $8,000](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=121983&pid=3845&totl=0&tuit=1000&hous=2000&book=1000&tran=1000&othr=3000&pelg=0&schg=1000&stag=1100&othg=1200&mta=1300&gib=1400&wkst=50&ppl=1300&parl=1200&perl=0&subl=0&unsl=0&gpl=8000&prvl=0&prvi=4.55&prvf=2.1&insl=0&insi=5&inst=36&oid=9e0280139f3238cbc9702c7b0d62e5c238a835d0#info-right)
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
## Animated GIF

30-rock-bad-ideas

### CODE REVIEW

**Comment by higs4281** [comment]
limits work, but I noticed this oddity: If I up personal/family contributions to cover costs, making loans unnecessary, the text says I'm borrowing "$0 more" than needed, rather than the overage amount.

zero-more

this doesn't happen on build:

nonzero-more

**Comment by mistergone** [comment]
This does happen on build - if your grants and savings are more than costs, but your loans are $0. I'm fixing it.

**Comment by mistergone** [comment]
I pushed a commit which should fix overborrowing messages - please check it out.

**Comment by higs4281** [comment]
Errant '$0 more' is gone, but we lost the line saying you're borrowing too much.

zero-gone

**Comment by mistergone** [comment]
Can you give me the offer you're using? My overborrowing error shows up locally. I'm sure you already `npm install`ed but uh... make sure your `student-debt-calc` is 2.6.0?

**Comment by mistergone** [comment]
Sorry, I found the bug and fixed it in an additional commit.

**Comment by higs4281** [comment]
👍 that fixed my bug:

good_graf

**Comment by marteki** [comment]
And a 👍  from me. Stellar fixing work, sir.

**Comment by mistergone** [comment]
Merging!

**Pull request merged**
