### PR TITLE
Update toggle functionality, interactions, and dynamic content

### PR DESCRIPTION
**Pull request by marteki**
This fixes some issues with the loan repayment toggles to make them work as designed and intended. It also includes some updates to our NPM packages.
## Changes
- Toggles change all relevant values on the page, not just the ones in their subsection
- Toggles and related dynamic content only appear if total federal loan debt at graduation is over $30,000. Otherwise, the loan term is set to 10 years and the ability to toggle with radio buttons is removed. Total federal loan debt is composed of Perkins, Direct unsubsidized, Direct subsidized, and Grad Plus loans.
- Updates to NPM package dependencies and package shrinkwrapping
## Testing

Pull down the branch, run `./setup.sh` and [take an example settlement school for a spin](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=449898&pid=1509&oid=fa8283b5b7c939a058889f997949efa566c616c6&tuit=44565&ppl=0&subl=3500&gpl=0&perl=5500&book=500&gib=0&pelg=1500&ta=500&unsl=6000&insi=5.0&parl=7000&insl=3000&stag=2000&prvl=17000&prvi=4.55&prvf=3&wkst=1000&hous=3000&othg=100&tran=500&schg=2000&mta=0&othr=500).
- All JS unit tests should pass.
- All JS browser tests should pass.
- Our NPM package security tests are reporting:
  
  > Tested 385 dependencies for known vulnerabilities, found 1 vulnerability, 9 vulnerable paths.
  
  These vulnerabilities are coming from the upstream dependencies of one of our dependencies. We'll be working to address it in that package, and with that package's dependencies. (Insert joke about the NPM ecosystem here.)
## Review

Any two thumbs from:
- @mistergone @niqjohnson @anselmbradford @higs4281 @amymok 
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by higs4281** [comment]
all tests run but perkins loans are not showing up

**Comment by marteki** [comment]
I didn't change any code for showing/hiding Perkins loans. That doesn't mean that I can't fix it. 😄 

Stand by for incoming commits.

**Comment by marteki** [comment]
Update: the school Bill was using to test doesn't offer Perkins loans. Even if the value is passed in the URL, it won't show on the page. 😀

**Comment by higs4281** [comment]
👍 mea culpa. toggles appear/disappear and calculations work as advertised. nicely done!

**Comment by marteki** [comment]
Forgot that with reduced resourcing, we'd decided that one thumb is good enough. Merging this.

**Pull request merged**
