### PR TITLE
Updates to functional testing and calculations

### PR DESCRIPTION
**Pull request by mistergone**
This pull request should bring everything in Part 1 into line, and **all functional tests for part 1 now pass**.
## Additions
- Page now properly handles and displays percentage values (displays as percent, calculates with decimal value)
-  Page now has a 500 millisecond delay when a user edits an input before calculating and changing the field. This delay is reset on each keyup.
## Changes
- Changes to URL handling so that all values are taken in properly
- Added parent loans and parentPLUS loans (when received through URL query) to family contributions
- Recalculated each functional test and correct the test values
- Changes to DOM so that "remaining cost" has two distinct values ("remaining cost after contributions" and "remaining cost after loans")
- Updated `student-debt-calc` to latest version
## Testing
- Pull it on down, check out those functional tests, and poke around Part 1!
## Review
- @marteki and @niqjohnson and @higs4281 and @ascott1 (if he's bored)
## Screenshots

screen shot 2016-02-02 at 11 14 29 am
## Todos
- **Part 2's functional tests are failing!** But I considered that out of scope for this PR. I will look at them very soon.
- Add in currency formatting. This will also require changing all the functional tests so they look for properly formatted numbers. And probably even more fiddling beyond that.
## Checklist
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [ ] Passes all existing automated tests
- [ ] New functions include new tests
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Visually tested in supported browsers and devices 
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
## Special Thanks

Continuing thanks to @marteki and @niqjohnson for all their work on the front-end!
## Animated GIF

**How this Team feels about passing functional tests:**
nerd-party

### CODE REVIEW

**Comment by marteki** [comment]
That GIF and its caption? :100: percent accurate.

Quick take:
- I'm seeing a NaN error for "money your family will provide", probably related to the parental loans:

screen shot 2016-02-02 at 11 53 42 am

@ascott1 had a similar problem in https://github.com/cfpb/college-costs/pull/61#issuecomment-171792728 when dealing with parent loans.

I think that NaN bug is causing one of the functional tests to fail that should be passing.

> Failures:
> 1) A dynamic financial aid disclosure that's required by settlement should properly update when a private loan is modified
>   Message:
>     Expected '-474' to equal '-1474'.

**Comment by marteki** [comment]
NaNs aside, the functional spec and tests look fantastic!

**Comment by marteki** [comment]
Alright, I found two more oddities UI-wise:

Private loan rate percentage:
screen shot 2016-02-02 at 12 56 27 pm

Total debt after repayment has unrounded decimal places ($198710.460432):
screen shot 2016-02-02 at 12 56 55 pm

All three of the things I found might be related.

**Comment by mistergone** [comment]
@marteki and I figured out that I was using an old URL query structure, so I've updated the code to reflect changes in the URL query structure.

**Comment by marteki** [comment]
NaNs are gone!
All relevant functional tests are passing (so only six failures)!
Interest rate is properly formatted!
And a bonus: the remaining cost is allowing a negative number!

:dancer: :dancer: :dancer:
:+1: :+1: :+1:

**Comment by mistergone** [comment]
Merging! :rocket: :octopus:

**Pull request merged**
