### PR TITLE
Add basic handling of multiple private loans

### PR DESCRIPTION
**Pull request by mistergone**
This PR adds basic support for multiple private loans. As an important note, totals are not currently being calculated or displayed correctly. I decided that fix was out of scope for this PR, as it will involve another update to student-debt-calc. So, that will come soon!

**Known bug**: Removing every private loan makes it impossible to add new private loans. My question is, "Should the user be able to remove the last private loan"? When we answer this, I will implement a fix one way or the other.
## Additions
- Added user interface for adding and removing private loans
- Update version of student-debt-calc to support multiple private loans
- Updated dispatchers to handle multiple private loans
## Testing
- Create a branch locally called `chuckisgreat`, then switch to that branch and pull in my latest repo. Fire up the old `runserver` and then try to add and remove private loans!
## Review
- @ascott1 @marteki @niqjohnson @higs4281 
## Screenshots

screen shot 2016-01-14 at 11 11 15 am
## Todos
- Fix loan totals to display proper numbers
- Address "removing all private loans" bug, as detailed above
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices 
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
## Special Thanks

@ascott1 and @marteki and @niqjohnson  and @higs4281 :  **Thanks for doing all this great work in my absence!!!**
## Animated GIF

murdock-winks

### CODE REVIEW

**Comment by ascott1** [comment]
@mistergone I'll add to the TODO that this doesn't update the loan totals in the UI, but otherwise works as expected.

**Comment by ascott1** [comment]
Small comment above, otherwise :+1:

**Comment by niqjohnson** [comment]
Styles are looking good at all the screen sizes I tested at.

I'm seeing a console error of `Uncaught TypeError: Cannot read property 'amount' of undefined` if I follow these (admittedly unlikely) steps, though:
1. Add a second private loan
2. Remove the **first** private loan
3. Change the value of any of the remaining private loan fields

Also, I think we decided that the user would be allowed to remove the last private loan. @caheberer, does that sound right to you?

**Comment by marteki** [comment]
From our discussion on a private repo:

> - The "Add another private loan" button inserts another set of private loan fields (amount, rate, fees, grace period, term) below the last set.
> - **Will there be a "remove private loan" button on loans two, three, etc.?**
> 
> No JS: Display three sets of private loan sections by default.
> 
> Full JS: Display one by default, as well as the add private loan button. Also, add a remove private loan button.

~~I'm reading this as only loans two, three, or up would have a remove button.~~ Never mind, I was reading it wrong. For full JS, display one loan with both add and remove buttons.

**Comment by higs4281** [comment]
:+1:  works as described

**Comment by marteki** [comment]
Works as described. Seeing the same console error as Niq, but that's probably due to not all the JS being hooked up yet.

:+1: for merging from me, assuming that we work together to add functional test coverage with the JS hookups.

**Comment by mistergone** [comment]
I'm going to merge this just to get it underway, then file issues about the following:
- Bug when adding then deleting a school, per @niqjohnson and @marteki 
- Create functional test coverage
- Enumerating IDs in each private loan
- NoJS view

**Pull request merged**
