### PR TITLE
Fixes, Round 2

### PR DESCRIPTION
**Pull request by mistergone**
This PR addresses the following bugs:
- 0% interest rates cause NaN results
- Perkins loan input appears when school does not offer Perkins loans
- Over-cap error messages contained 'NaN' for grad programs
## Changes
- Update to `student-debt-calc` to version 2.5.7, which fixes issues with 0% interest rates
- Added code to hide Perkins loans for schools that do not offer it
- Fixed code which determined graduate program caps
## Testing
- Passes unit tests
- Functional tests are currently not passing
## Review
- @marteki and @higs4281 and @ans - Pull it down, `npm install`, `gulp`, and check out the the bug fixes! 
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
## Animated GIF

fixed-it

### CODE REVIEW

**Comment by higs4281** [comment]
👍 bugs fixed as advertised.

**Comment by marteki** [comment]
Bugs fixed! I discovered a separate bug that relates to Grad PLUS loans, but this PR gets a 👍  to merge from me. (Even with the lack of a changelog entry. 😄 )

**Comment by mistergone** [comment]
I'm still not 100% sure if I'm philosophically aligned with bug fixes going in the CHANGELOG, but I did it for @marteki 

Merging!

**Comment by saintsoup52** [comment]
I will have to review these updates this afternoon (sorry have to go pick up the kiddos)

**Pull request merged**
