### PR TITLE
Adjust salary variable names for clarity

### PR DESCRIPTION
**Pull request by higs4281**
Our variable names evolved from a blending of legacy code and new data
sources, and in many cases became confusing. Salary is especially so.
Since we need to be clear about which source is being used for salary
figures -- program data or school data -- This renames the json salary
variables to `programSalary`,  `schoolSalary`, and `nationalSalary`.
## Changes
- json variable names
- matching usage in school-model.js
## Testing
- Run `gulp` and then check that salary info in Step 2 still shows up correctly (should be $38,200). [standalone debt-burden example](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=366748&pid=627&totl=120443&tuit=31122&hous=5600&book=1000&tran=0&othr=4768&pelg=0&schg=0&stag=0&othg=0&mta=0&gib=0&wkst=0&ppl=0&parl=0&perl=0&subl=0&unsl=20500&gpl=21990&prvl=0&prvi=7.9&prvf=0&insl=0&insi=4&inst=60&oid=9e0280139f3238cbc9702c7b0d62e5c238a835d0)
## Review
- @mistergone @marteki 
## Checklist
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by higs4281** [comment]
@mistergone Occurs to me that we could go full-monty and rename the natstats variable to `nationalSalary`

**Comment by mistergone** [comment]
@higs4281 - I'm 100% fine with that. The more differentiation, the better, honestly.

**Comment by amymok** [comment]
Looks great!

**Comment by higs4281** [comment]
@mistergone done. pls review!

**Comment by mistergone** [comment]
I was able to pull it down and get it working, so 👍

**Pull request merged**
