### PR TITLE
Dynamic changes based on whether salary data is from program vs school vs national

### PR DESCRIPTION
**Pull request by marteki**
This switches salary content to school phrasing if we have no program salary data, hides content entirely if only national is available (along with popping a warning that we don't have relevant data). 

This also makes some program vs school level tweaks to wording in the graph of the graduation rate and loan default rate metrics, and updates our loan origination fee displays to work with the newly corrected constants.
## Additions
- Hides salary content with a warning if only national data available
## Changes
- Switches salary content to school phrasing if we have no program salary data
- Tweaks wording around program vs school level for metric graphs
- Updates loan origination fee displays to work with corrected constants
## Testing

Pull down the branch, make sure to `manage.py loaddata collegedata`, and run `gulp`.

~~Here's an offer with salary data at the program level.~~ (Removed, because it was a legacy link to a non-actual program.)
[Here's one without salary data at the program level.](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=182111&pid=1412&oid=fa8283b5b7c939a058889f997949efa566c616a6&book=0&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=90175&tran=500&tuit=86975&unsl=2000&wkst=1000)
[Here's one without salary data at the program or school level.](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=480073&pid=2932&oid=fa8283b5b7c939a058889f997949efa566c616a1&book=1500&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=83450&tran=500&tuit=20862&unsl=2000&wkst=1000)

[Here's a program without program level graduation rate data.](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=145770&pid=1380&oid=9e0280139f3238cbc9702c7b0d62e5c238a835a0&book=650&gib=3000&gpl=1000&hous=3000&insi=4.55&insl=3000&inst=36&mta=3000&othg=100&othr=500&parl=10000&pelg=1500&perl=3000&ppl=1000&prvl=3000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=62795&tran=500&tuit=60895&unsl=2000&wkst=3000) Check the change in helper text wording in the graph metric.
[Here's one without program level loan default rate data.](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=436094&pid=2575&oid=fa8283b5b7c939a058889f997949efa566c616a7&book=800&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=24224&tran=500&tuit=23424&unsl=2000&wkst=1000)

And [the new loan origination fee rates should be properly displayed on the About This Tool page](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/about-this-tool/).
- All unit tests should pass.
- All NPM security tests should pass.
- The bulk of our functional tests are still failing.
## Review
- @mistergone @higs4281 @amymok 
## Todos
- Discussion internally happening around what to do with the budget worksheet when we have no program or school salary data
## Screenshots

Posted below.
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [ ] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by marteki** [comment]
How the salary section should look if we have program level data

screen shot 2016-08-04 at 10 15 59 am

How the salary section should look if we have only school level data

screen shot 2016-08-04 at 10 15 33 am

How the salary section should look if we only have national level data

screen shot 2016-08-04 at 10 15 18 am

**Comment by mistergone** [comment]
Looks good to me! 👍

**Comment by higs4281** [comment]
👍 Working for various examples, and the constants, as advertised. very nice.

Note:  
Using this [standalone school/program pair](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=480082&pid=3681&oid=fa8283b5b7c939a058889f997949efa566c616a2&book=1500&gib=0&gpl=0&hous=5611&insi=5.0&insl=3000&inst=36&mta=0&othg=100&othr=6079&parl=7000&pelg=1500&perl=5500&ppl=0&prvl=2000&prvf=2.1&prvi=4.55&schg=2000&stag=2000&subl=3500&totl=98611&tran=500&tuit=24040&unsl=2000&wkst=1000#info-right), which has no salary value for program or school, the "How do I know" section appears as you show it, but, as noted, the "How will I afford" budget worksheet section still displays the national salary value.

**Comment by marteki** [comment]
@higs4281 I brought up the section that still shows the national salary value, it was affirmed as something we need to address by @saintsoup52, and a new issue was created for it internally. It will be addressed in a separate PR.

Merging this one!

**Comment by higs4281** [comment]
For posterity, there are no EDMC programs with salary values, but I created one locally with a salary value for testing, and it worked.

**Pull request merged**
