### PR TITLE
Add interaction between Step 1 and Step 2

### PR DESCRIPTION
**Pull request by marteki**
This adds a new button interaction after Step 1. Only after clicking the button is Step 2 revealed.

step 1 to step 2

I also fixed some linting issues.
## Additions
- Add "Continue to Step 2" interaction right after Step 1.
## Changes
- Revised `.eslintrc` for version 2 of package.
- Fixed a bunch of `gulp lint` errors. No more red errors, just warnings.
- Updated our browser tests. Little green dots, everywhere.
## Testing

Pull down this branch.
- Run `gulp lint`. You should get the following results for the gulp scripts:
  
  > ✖ 1 problem (0 errors, 1 warning)
  
  And the following for the app files:
  
  > ✖ 71 problems (0 errors, 71 warnings)
- Make sure that you've [followed the directions in the README to setup up functional testing](https://github.com/cfpb/college-costs/), then run `protractor test/functional/conf.js`. You should see something reasonably close to the following:
  
  > Using the selenium server at http://localhost:4444/wd/hub
  > [launcher] Running 1 instances of WebDriver
  > Started
  > ...............................................................
  > 63 specs, 0 failures
  > Finished in 183.155 seconds
- Run `gulp`, then `manage.py runserver`, then [view this link in a browser](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=449898&pid=1509&oid=fa8283b5b7c939a058889f997949efa566c616c6&tuit=44565&ppl=0&subl=3500&gpl=0&perl=5500&book=500&gib=0&pelg=1500&ta=500&unsl=6000&insi=5.0&parl=7000&insl=3000&stag=2000&prvl=17000&prvi=4.55&wkst=1000&hous=3000&othg=100&tran=500&schg=2000&mta=0&othr=500). The interaction should work as designed, and as depicted above in the animated GIF.
## Review
- @mistergone @higs4281 @amymok 
## Todos
- I want to fix all our lint warnings.
- I will refactor our browser tests, especially stopping the overuse of `browser.wait()`.
- EDITED TO ADD: I still want to automate our front-end unit and browser tests. Integration into Travis and all that. 😃 
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by higs4281** [comment]
👍 this works for me, but I see the 'hidden' blue in-focus rule

**Comment by marteki** [comment]
@higs4281 So you're saying that I should highly prioritize tweaking that? 😛  Doable.

**Comment by mistergone** [comment]
👍 This works, and the focus blue doesn't hurt me.

**Comment by marteki** [comment]
Can folks recheck this, specifically to see if the blue focus line is still appearing? Bonus points for navigating by keyboard rather than by mouse.

**Comment by marteki** [comment]
Thank you to @KimberlyMunoz for taking a look at this with me, and giving dispensation to use `outline: none` and added JS in this instance.

**Comment by higs4281** [comment]
:boom: blue line gone in chrome and safari 👍 
and tab navigation is smooth.

**Pull request merged**
