### PR TITLE
Implements url2 scheme and passing url_base to templates

### PR DESCRIPTION
**Pull request by higs4281**
Short description explaining the high-level reason for the pull request
## Additions
- new urls
## Removals
- none
## Changes
- Updates test to match
## Testing
- in standalone, site will render under /paying-for-college2/
  I propose we leave the README as is until launch, unless someone complains.
## Review
- @ascott1 (the real one)
- @kurzn could you peek at the url changes to make sure they're what we want?
- @niqjohnson

### CODE REVIEW

**Comment by niqjohnson** [comment]
:+1:

Everything shows up under /paying-for-college2/ for me in standalone.

**Comment by marteki** [comment]
Working for me in standalone under /paying-for-college2/. A negative test where I purposefully put in the wrong URL shows a list of the correct URLs in the 404 error.

:+1:

**Comment by ascott1** [comment]
I just tested this in standalone and it is working great for me as well. :+1:

**Comment by kurzn** [comment]
Looks great!

**Pull request merged**
